language: java
dist: trusty
os:
  - linux

jdk:
  - oraclejdk8
  
sudo: false
addons:
  chrome: stable

env:
  global:
    - workingDir=$(pwd)    
  matrix:
    - MODE=e2e_cits TEST=smoke
    - MODE=e2e_cits TEST=basic_search_cortanna

jobs:
  include:
    - stage: Deploy
      env: "DEPLOY_MODE=build"

before_install:
  # source the env.sh script to get exported variables
  - source ./scripts/ci/env.sh print
  - curl -sL https://raw.githubusercontent.com/x0156/cits-travis-seed/$TRAVIS_BRANCH/install.sh | bash
  - . ./sourcefile

install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
 
before_script:  
  - "echo 'echo $*;exit 1;' > fail;chmod u+x fail;"
  - chmod -R +X ./scripts
 
script:
  - ./scripts/ci/travis-script.sh
  
after_script:
  - echo "Reports (in $reportDir):";ls $reportDir
