language: java
jdk:
  - oraclejdk8
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - export CITS_VERSION=1.0-SNAPSHOT
  - export CITS_TAG=v1.0-snapshot
  - export CITS_REPO=CognizantQAHub/Cognizant-Intelligent-Test-Scripter
  - export CITS=Run.command
  - curl -O -L "https://github.com/$CITS_REPO/releases/download/$CITS_TAG/cognizant-intelligent-test-scripter-$CITS_VERSION-setup.zip"
  - unzip "cognizant-intelligent-test-scripter-$CITS_VERSION-setup.zip"
  - cd "cognizant-intelligent-test-scripter-$CITS_VERSION"
  - chmod u+x Run.command
  - ./$CITS -version
 
before_script:
  - "echo 'echo $*;exit 1;' > fail"
  - export TEST="-project_location Projects/DemoProject -scenario BasicFeatures -testcase DemoTestCase -browser PhantomJS"
  
script: 
  - "./$CITS -run $TEST  -dont_launch_report"
  - "export failed=$(./$CITS  $TEST -latest_exe nofailTests)"
  - "export report=$(./$CITS  $TEST -latest_exe_loc)"

after_script:
  - "echo REPORTS(in $report):;ls $report"
  - "if [ $failed -ne 1 ]; then (./fail $failed Test/s failed); fi"
