language: java
dist: trusty
os:
  - linux

jdk:
  - oraclejdk8
  
sudo: false
addons:
  chrome: stable
  apt:
    packages:
      #- oracle-java8-installer
      #- google-chrome-stable
env:
  global:
    - workingDir=$(pwd)    
  matrix:
    - TEST=smoke
    - TEST=basic_search_cortanna

before_install:
  # source the env.sh script to get exported variables
  - source ./scripts/ci/env.sh print
  - curl -sL https://raw.githubusercontent.com/x0156/cits-travis-seed/$TRAVIS_BRANCH/install.sh | bash
  - . ./sourcefile

install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
 
before_script:  
  - "echo 'echo $*;exit 1;' > fail;chmod u+x fail;"
  - TEST=$(resolve $TEST)
 
script: 
  - "CITS -run $TEST  -dont_launch_report -standalone_report -setEnv $citsEnv"
  - "export reportDir=$(CITS  $TEST -latest_exe_loc);CITS  $TEST -latest_exe_data_raw > report.json;"
  - "failed=$(CITS  $TEST -latest_exe nofailTests);if [ $failed -ne 0 ]; then (./fail $failed Test/s failed); fi"
  
after_script:
  - echo "Reports (in $reportDir):";ls $reportDir
