language: java
jdk:
  - oraclejdk8
sudo: false
addons:
  apt:
    packages:
      #- oracle-java8-installer
before_install:
  - export projectDir=$(pwd)
  - curl -sL https://raw.githubusercontent.com/x0156/cits-travis-seed/install2/install.sh | bash
  # install the sourcefile to update PATH and CIST_ROOT (./lib/cits/)
  - . ./sourcefile
  
before_script:
  - "echo 'echo $*;exit 1;' > fail;chmod u+x fail;"
  # export TEST="-project_location Projects/Bing -release early -testset smoke"
  - export TEST="-project_location $projectDir/Projects/Bing -scenario basic_search -testcase cortanna -browser PhantomJS"
  
script: 
  - "CITS -run $TEST  -dont_launch_report -standalone_report"
  - "export reportDir=$(CITS  $TEST -latest_exe_loc);CITS  $TEST -latest_exe_data_raw > report.json;"
  - "failed=$(CITS  $TEST -latest_exe nofailTests);if [ $failed -ne 0 ]; then (./fail $failed Test/s failed); fi"
  
after_script:
  - echo "Reports (in $reportDir):";ls $reportDir
